# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-12 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StarDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='球星名')),
                ('introduce', models.TextField(max_length=1000, verbose_name='介绍')),
            ],
            options={
                'verbose_name_plural': '球星',
                'verbose_name': '球星',
            },
        ),
    ]
