# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-13 13:26
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('content', DjangoUeditor.models.UEditorField(max_length=200, verbose_name='content')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='time')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comment',
            },
        ),
        migrations.AlterModelOptions(
            name='stardetail',
            options={'verbose_name': 'star', 'verbose_name_plural': 'star'},
        ),
        migrations.AlterField(
            model_name='stardetail',
            name='introduce',
            field=DjangoUeditor.models.UEditorField(max_length=1000, verbose_name='introduce'),
        ),
        migrations.AlterField(
            model_name='stardetail',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.StarDetail'),
        ),
    ]
